In [126]:
# Ignore unnecessary padas warnings
import warnings
warnings.simplefilter(action = 'ignore', category = FutureWarning)

# API
import requests
import json

# AquaCrop
from aquacrop import AquaCropModel, Soil, Crop, InitialWaterContent, IrrigationManagement

# General
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime

### Get Weather Forecast

To create an AquaCrop model we need either observed or forecasted weather data. Specifically we need min and max daily temperature, total daily precipitation, and reference evapotranspiration. To get this data we will use Meteo-Open API that provides both hourly and daily forecasts for free for any specified latitude and longitude.

In [134]:
# Mango farm in Spain (Finca Los Pepenos)
lat = 36.80
long = -4.19

# Daily weather parameters
daily_params = ["temperature_2m_max", "temperature_2m_min", "precipitation_sum", "et0_fao_evapotranspiration"]

# Timezone
timezone = "auto"

# Forecast period
start_date = "2023-01-26"
end_date = "2023-01-31"

# All params
params = {"latitude": lat, "longitude": long, 
          "daily": daily_params, "timezone": timezone,
          "start_date": start_date, "end_date": end_date}

# Default API url
api_url = "https://api.open-meteo.com/v1/forecast"

# API call
response = requests.get(api_url, params = params)
data_units = response.json()["daily_units"]
data = pd.DataFrame(response.json()["daily"])
data

,time,temperature_2m_max,temperature_2m_min,precipitation_sum,et0_fao_evapotranspiration
0,2023-01-26,13.1,4.4,0.0,1.25
1,2023-01-27,14.9,4.6,0.0,1.46
2,2023-01-28,13.5,4.6,0.0,1.24
3,2023-01-29,12.1,2.9,0.1,0.85
4,2023-01-30,13.0,3.9,0.0,0.86
5,2023-01-31,15.1,4.3,0.0,1.05

### Initializing the AquaCrop model

Notes for successful initialization:
- weather data must be available for the entire planting period thus the `planting_date` of the crop must be the first date in the weather data series (unless we are also simulating the waterbalance before planting)
- weather data must be in a DataFrame with specified column names, all data points as floats and the `weather_df.Date` as a `Timestamp` object
- simulation start and end dates must be in the `"%Y/%m/%d"` format

In [136]:
def rewriteOpenMeteoData(df):
    # Basic error handling
    if type(data) != pd.core.frame.DataFrame:
        raise Exception("The input data is not a Pandas DataFrame")
        
    # Renaming dictionary
    colnames_dict = {"MinTemp": "temperature_2m_min",
                     "MaxTemp": "temperature_2m_max", 
                     "Precipitation": "precipitation_sum", 
                     "ReferenceET": "et0_fao_evapotranspiration", 
                     "Date": "time"}
    
    # Apply reordering and renaming
    colnames_order = list(colnames_dict.values())
    df = df[colnames_order]
    df.columns = list(colnames_dict.keys())
    
    # Make DateTime objects
    df["Date"] = pd.to_datetime(df["Date"], format= "%Y-%m-%d")
    
    return df

# Define model parameters
soil = Soil(soil_type = 'SandyLoam')
crop = Crop('Tomato', planting_date = '01/26')
init_water = InitialWaterContent(value = ['FC'])
weather_df = rewriteOpenMeteoData(data)
sim_start_time = weather_df.Date.iloc[0].strftime("%Y/%m/%d")
sim_end_time = weather_df.Date.iloc[-1].strftime("%Y/%m/%d")

# Define Irrigation Management method
interval_irri = IrrigationManagement(irrigation_method = 2, IrrInterval = 2)

# Initialize field model
model = AquaCropModel(sim_start_time = sim_start_time,
                      sim_end_time = sim_end_time,
                      weather_df = weather_df,
                      soil = soil,
                      crop = crop,
                      initial_water_content = init_water, 
                      irrigation_management = interval_irri)
                      
# Run the simulation
model.run_model(till_termination = True)
model._outputs.final_stats

Empty DataFrame
Columns: [Season, crop Type, Harvest Date (YYYY/MM/DD), Harvest Date (Step), Yield (tonne/ha), Seasonal irrigation (mm)]
Index: []

### Running the Model and Querying Results

#### Running the Entire Control Period
To run the model for the entire period of available weather data the simplest command is `model.run_model(till_termination = True)`

#### Running a Specified Number of Days/Timesteps
To run the model for a predetermined number of steps one can run `model.run_model(N)` where $N$ is the integer number of days. Or one can first initialize the model with `model._initialize()` and then run `model.run_model(initialize_model = False)` which runs the model for a single timestep.

#### Retrieving results
When the model terminates, it includes the following attributes:
- `_outputs`
    - `_outputs.final_stats` or `model.get_simulation_results()`: dataframe with final results including the season counter, crop type, harvest date, growing length, yield, and amount of total irrigation
    - `_outputs.water_flux` or `model.get_water_flux()`: 2D array where rows are days and cols are various water inflows and outflows
    - `_outputs.water_storage` or `model.get_water_storage()`: 2D array where rows are days and cols are amounts of water stored across soil compartments
    - `_outputs.crop_growth` or `model.get_crop_growth()`: 2D array where rows are days and cols are amounts of various parameters of crop growth
- `_weather`
    - the dataframe of the input weather data
- `_init_cond`
    - all the initial conditions at the beginning of the current timestep. Used to check e.g. current depletion or total available water. Reference in [/entities/initParamVariables.py](https://github.com/aquacropos/aquacrop/blob/master/aquacrop/entities/initParamVariables.py)
- `_clock_struct`
    - time and date related variables such as current step counter, harvest day, planting day, season counter, etc. Reference in [/entities/clockStruct.py](https://github.com/aquacropos/aquacrop/blob/master/aquacrop/entities/clockStruct.py)
- `_param_struct`
    - all parameters that don't change over the course of the simulation. E.g. crop types, field management practices, soil type, and other soil related features like hydrology. Reference in [/entities/paramStruct.py](https://github.com/aquacropos/aquacrop/blob/master/aquacrop/entities/paramStruct.py)

In [142]:
# Water flux data
model.get_water_flux()

,time_step_counter,season_counter,dap,Wr,z_gw,surface_storage,IrrDay,Infl,Runoff,DeepPerc,CR,GwIn,Es,EsPot,Tr,TrPot
0,0.0,0.0,1.0,64.77,-999.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,1.230882,1.37500,0.000000,0.000000
1,1.0,0.0,2.0,63.58,-999.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,1.185135,1.60600,0.000000,0.000000
2,2.0,0.0,3.0,66.25,-999.0,0.0,4.026000,4.026000,0.0,0.000000,0.0,0.0,1.364000,1.36400,0.000000,0.000000
3,3.0,0.0,4.0,65.26,-999.0,0.0,0.000000,0.100000,0.0,0.166671,0.0,0.0,0.866292,0.92293,0.011897,0.011897
4,4.0,0.0,5.0,72.59,-999.0,0.0,1.704827,1.704827,0.0,0.059216,0.0,0.0,0.932200,0.93220,0.013603,0.013603
5,0.0,0.0,0.0,0.00,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.00000,0.000000,0.000000

In [143]:
# Water storage data
model.get_water_storage()

,time_step_counter,growing_season,dap,th1,th2,th3,th4,th5,th6,th7,th8,th9,th10,th11,th12
0,0.0,1.0,1.0,0.207691,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000
1,1.0,1.0,2.0,0.195840,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000
2,2.0,1.0,3.0,0.222460,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000,0.220000
3,3.0,1.0,4.0,0.212319,0.220203,0.220135,0.220099,0.220061,0.220046,0.220036,0.220029,0.220025,0.220022,0.220019,0.220017
4,4.0,1.0,5.0,0.219909,0.220019,0.220012,0.220010,0.220010,0.220009,0.220008,0.220007,0.220007,0.220006,0.220006,0.220005
5,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [144]:
# Crop growth data
model.get_crop_growth()

,time_step_counter,season_counter,dap,gdd,gdd_cum,z_root,canopy_cover,canopy_cover_ns,biomass,biomass_ns,harvest_index,harvest_index_adj,yield_
0,0.0,0.0,1.0,1.75,1.75,0.300000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
1,1.0,0.0,2.0,2.75,4.50,0.300000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
2,2.0,0.0,3.0,2.05,6.55,0.300000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0
3,3.0,0.0,4.0,0.50,7.05,0.300000,0.007538,0.007538,0.283020,0.283020,0.0,0.0,0.0
4,4.0,0.0,5.0,1.45,8.50,0.326464,0.008524,0.008524,0.602855,0.602855,0.0,0.0,0.0
5,0.0,0.0,0.0,0.00,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0

In [151]:
# Soil profile parameters
model._param_struct.Soil.profile

,Comp,Layer,dz,dzsum,zBot,z_top,zMid,th_dry,th_wp,th_fc,th_s,Ksat,penetrability,tau,th_fc_Adj
0,0,1,0.1,0.1,0.1,0.0,0.05,0.05,0.1,0.22,0.41,1200,100,1,0.22
1,1,1,0.1,0.2,0.2,0.1,0.15,0.05,0.1,0.22,0.41,1200,100,1,0.22
2,2,1,0.1,0.3,0.3,0.2,0.25,0.05,0.1,0.22,0.41,1200,100,1,0.22
3,3,1,0.1,0.4,0.4,0.3,0.35,0.05,0.1,0.22,0.41,1200,100,1,0.22
4,4,1,0.1,0.5,0.5,0.4,0.45,0.05,0.1,0.22,0.41,1200,100,1,0.22
5,5,1,0.1,0.6,0.6,0.5,0.55,0.05,0.1,0.22,0.41,1200,100,1,0.22
6,6,1,0.1,0.7,0.7,0.6,0.65,0.05,0.1,0.22,0.41,1200,100,1,0.22
7,7,1,0.1,0.8,0.8,0.7,0.75,0.05,0.1,0.22,0.41,1200,100,1,0.22
8,8,1,0.1,0.9,0.9,0.8,0.85,0.05,0.1,0.22,0.41,1200,100,1,0.22
9,9,1,0.1,1.0,1.0,0.9,0.95,0.05,0.1,0.22,0.41,1200,100,1,0.22
10,10,1,0.1,1.1,1.1,1.0,1.05,0.05,0.1,0.22,0.41,1200,100,1,0.22
11,11,1,0.1,1.2,1.2,1.1,1.15,0.05,0.1,0.22,0.41,1200,100,1,0.22

In [152]:
# Soil hydrology parameters
model._param_struct.Soil.Hydrology

,Comp,zBot,z_top,zMid,th_dry,th_wp,th_fc,th_s,Ksat,penetrability,tau,th_fc_Adj,dz
Layer,,,,,,,,,,,,,
1,5.5,0.65,0.55,0.6,0.05,0.1,0.22,0.41,1200.0,100.0,1.0,0.22,1.2